version: 2
updates:
  - package-ecosystem: gomod
    directory: /go-version
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      semver-major-days: 30
    open-pull-requests-limit: 5

  - package-ecosystem: uv
    directory: /py-version
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      semver-major-days: 30
    open-pull-requests-limit: 5
